# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mehdy's blog
email: me@mehdy.net
description: >
 I am a developer trying to be a hacker.
 I'm mostly interested in python, golang, erlang, rustlang,
 JS, noSQL, AI, NLP, CV, Linux, cloud, OpenStack, big data.
 I write about everything new I learn :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.mehdy.net" # the base hostname & protocol for your site
twitter_username: mehdy314
github_username:  mehdy

# Build settings
markdown: kramdown
